### ISSUE TITLE
Schaar Kernel

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce-2014-cw1#15]
I found that using rand(n) and comparing the outputs of schaar_scalar and my various vectorised versions are very very very slightly different, but using images like pear or cameraman, the asserts pass...

I went back to t3 = effects.scharr_scalar([0.5 0.6 0.7; 0.5 0.6 0.7; 0.5 0.6 0.7]); % == 0.4, which I had previously ignored, because whilst the console shows my t3 = 0.4, if I equate them they're not the same and out by   -1.1102e-16, is this significant enough? The schaar scalar is correct according to the other tests, and the cameraman image though

**Comment by m8pple** [comment]
You're seeing floating-point representation problems here, as:

```
>> log2(1.1102e-16)
ans =
    -53.0000299199857
```

So it's because the resolution of double-precision numbers is 2^-53 at this point.

So the comments on #13 apply here as well, though for a different reason. I probably
shouldn't have chosen to do the image processing floating-point; previous years
people have had problems with integer conversions, but apparently floats throw
up problems as well.
