### ISSUE TITLE
10% or Better  - Reliable Timing

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce-2014-cw1#4]
Does this condition just mean, if I were to run the timer function on the same function twice, both results should be within 10% of each other?

**Comment by m8pple** [comment]
I updated the doc-string to make the meaning of relative error a little clearer.

I've still left it deliberately vague as to what the "true" time of a function is; your
definition makes an appeal to some intuitive notion of stability and  repeatability,
which I think is a good way of looking at it.

(Leaving open, in case there are other comments).

**Comment by kronocharia** [comment]
Given we're trying to create a reliable timing function, we need to use some other method of timing it to verify "true time"? Unless it's computed relative to itself, which would be something to do with repeatability... Also I guess we disabled CPU throttling at our own risk?

**Comment by m8pple** [comment]
I think you've hit on one of the "deep" problems here, which is: the performance of matlab functions is deeply dependent on the matlab environment, so is it actually possible to work out what the "true" time is from outside matlab? (Short answer: no)

So I think the notion of relativism and repeatability is the important one, plus the idea that the measured time should (as much as possible) reflect the function being measured, not the thing doing the measuring.

**Comment by kronocharia** [comment]
But no matter how many times I call a function and measure it in a group, I cant reduce the overhead of the actual function handle calling part and average it away, can I?

**Comment by davidfof13** [comment]
Aren't we allowed to compute the true execution time outside of  the 'function_time' function?

**Comment by m8pple** [comment]
@kronocharia You're right, the function calling overhead is impossible to separate from the execution of the function itself. It is entirely possible that for: 

```
f=@myFunction;
g=@()(myFunction());
```

You might see different execution times due to the different ways the underlying function is being called. However, given a particular function, and not knowing what is in it, one can only hope to time that function in its entirety, including the overhead associated with calling it.

@davidfof13 The problem is one of defining "true execution time" external to `function_time`. In the above example, should the baseline be `tic; myFunction(); toc` ? I would argue that the abstraction
cost of the "function", whatever kind of function it is, is part and parcel of the performance, as it
limits how often that function can be called.
