### ISSUE TITLE
Window size greater than image dimension (E2.2)

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw1#9]
f1=@(n)( render.apply_scalar( @effects.median_scalar, n, rand(100) ) );
f2=@(n)( render.apply_scalar( @effects.median_scalar, 4, rand(96+n) ) );
timing.plot_function_time_against_n( {f1, f2}, 4:1000 )

In function f1, the image dimension is always kept constant at 100x100 while the border size varies from 4:1000. There comes a point where the window size exceeds the image dimension when n=50. When that happens, the assert function in apply_scalar function line 22 throws an error.

assert(hOut>=1);
assert(wOut>=1);

timing.plot_function_time_against_n( {f1, f2}, 4:1000 ) will then throw an error and the graph would not get printed out.

**Comment by m8pple** [comment]
All the values given are suggestive rather than prescriptive. How far each machine gets into the graph will vary a lot depending on speed. I did it on a relatively slow machine, so I guess mine happened to finish just before the window threshold was hit. That said, many people will probably hit the problem.

Would a better command be:

```
timing.plot_function_time_against_n( {f1, f2}, 4:49)
```

or something else?

**Comment by bwh10** [comment]
Yes, I used the new command: timing.plot_function_time_against_n( {f1, f2}, 4:49) and it worked perfectly!
